### ISSUE TITLE
Feedback - much needed project

### ISSUE THREAD

**Issue by Rush** [braceslab/service-systemd#5]
Very cool project. I was actually going to build a similar one but you beat me to it. :)

List of suggestions:
- [x] --help should work fine without `sudo`
- [ ] User level services https://wiki.archlinux.org/index.php/Systemd/User
- [ ] --help should hint example usage, it should also hint which options are required
- [ ] Find default node location from `which node` - mine is at `/usr/local/nvm/versions/node/v8.1.3/bin/node`
- [ ] Allow setting environment with `EnvironmentFile` - I don't want my payment gateway keys to reside in the service file
- [ ] Application could ask for sudo only for root-critical tasks. For example `sudo cp /tmp/tmp.service > /etc/systemd/services/some.service`

**Comment by simone-sanfratello** [comment]
Hi,
thank you for feedbacks, those are good tips.

I'm going to do those and you are welcome if you want to contribute!

**Comment by Rush** [comment]
I did as you suggested but I'm seeing some anomalies right now - I'm unable to pass arguments to `-e` or `-E`. Looking into it.

**Comment by Rush** [comment]
Also, what's the Node version you're targeting for? The code looks like Node 4.

**Comment by simone-sanfratello** [comment]
Yes, the node version target was 4, I started the project some years ago. I should move at 6 since it's current LTS.

**Comment by simone-sanfratello** [comment]
I reverted the PR, there was some breaking changes.

**Comment by Rush** [comment]
Oh yeah. It was a work in progress. What are the breaking changes? I cannot make the old environment option to work.

**Comment by Rush** [comment]
I think my PR should look better now. Please test it yourself before merging. :)

**Comment by simone-sanfratello** [comment]
Thank you!
I'll test, or better I'll get the chance for setup tests, it will require a while but at this point it worth the effort.

Breaking changing was you removed the root checking at all and you didn't follow the code style, I use standard

**Comment by Stradivario** [comment]
Hi guys !! Thank you very much for your contributions to the community! I was just starting to write something like that and i saw this library! I am testing it at the moment and will let you know if i have some proposals. :)) 

Currently long term support versions are 8.9.4 and 10.13.0



Regards,
K.T.

**Comment by simone-sanfratello** [comment]
Hi @Stradivario, thank you!
Any feedback, proposal and PR are welcome!

I'm going to update the lib on January, upgrading node engine and adding tests, if you like to contribute I'll be very happy

**Comment by Stradivario** [comment]
Oh my god @simone-sanfratello gmail send me notification JUST now :D

**Comment by Rush** [comment]
Thanks for bumping the thread. I actually forgot about this library (even though I still use it, I did set up hosting for some of my things using it)
